--- 
USE_OCL: false
GITORIOUS_ROOT: git://gitorious.org
SPACEGIT_ROOT: git://spacegit.dfki.uni-bremen.de
SPACEGIT_PUSH_ROOT: "git@spacegit.dfki.uni-bremen.de:"
operating_system: 
- - ubuntu
  - debian
- - maverick
  - "10.10"
  - default
GITORIOUS_PUSH_ROOT: "git@gitorious.org:"
manifest_source: 
  branch: master
  url: git://spacegit.dfki.uni-bremen.de/avalon/buildconf.git
  type: git
ROCK_FLAVOR: master
GITORIOUS: git
SPACEGIT: git
rtt_corba_implementation: omniorb
osdeps_mode: all
rtt_target: gnulinux
